/** Export all segments **/
proc export
    data = arec559.PS_charge_con
    dbms = csv
    outfile = "/home/asaito10/AREC559/PS_charge_con.csv"
    replace;
run;

/*Create dataset with cm11, time, choice, spend for DiD*/
data PS_charge_con_cm11;
	set arec559.PS_charge_con (keep=cm11 time choice spend);run;


/*steps for GBM*/
/** Import Pscore generated by GBM.  **/
PROC IMPORT DATAFILE="/home/asaito10/AREC559/PS_charge_con_gbm.csv"
		    OUT=PS_charge_conR
		    DBMS=csv
		    REPLACE;
RUN;

/*Merge with PS_charge_con_cm11*/
/*check if; n=(T+C)*2 */
data PS_charge_con_gbm;
	merge PS_charge_con_cm11 PS_charge_conR;
	run;


/* Split into control and treatment */
data PS_charge_conR_treatment;
	set PS_charge_con_gbm (rename = (cm11 = idT pscore = pscoreT));
	where choice=1;
	keep idT pscoreT;
run;
data PS_charge_conR_control;
	set PS_charge_con_gbm (rename = (cm11 = idC pscore = pscoreC));
	where choice=0;
	keep idC pscoreC;
run;

/** MATCHING!! **/
%include '/home/asaito10/AREC559_programs/PSMatching (1).sas';
%PSMatching(datatreatment = PS_charge_conR_treatment, datacontrol = PS_charge_conR_control, method = NN, 
	numberofcontrols = 1, caliper = , replacement = yes, out = matches);
	
data arec559.PS_charge_conR_matches;
	set matches;
	run;
	
/* Merge control and treatment */

data PS_charge_conR_c;
	set arec559.PS_charge_conR_matches (keep=IdSelectedControl PScoreControl rename=(IdSelectedControl=cm11));
	run;
data PS_charge_conR_t;
	set arec559.PS_charge_conR_matches (keep=MatchedToTreatID PScoreTreat rename=(MatchedToTreatID=cm11));
	run;
data PS_charge_conR_matched;
	set PS_charge_conR_t PS_charge_conR_c;
	run;
	

/* Merge matched data with panel data */
proc sql;
	create table PS_charge_conR_DiD as
	select *
	from PS_charge_conR_matched as a
	left join arec559.panel_lab2 as b
	on a.cm11=b.cm11;
	quit;

data arec559.PS_charge_conR_DiD;
	set PS_charge_conR_DiD;
	interaction=time*choice;run;
	

/* Run diffrence in difference */
proc reg data=arec559.PS_charge_conR_DiD;
	model spend=time choice interaction;
	run;

/* means for each segment after matching */
proc means data=arec559.PS1R_DID;
	title "segment1";
	var spend;
	class time choice;
	run;
proc means data=arec559.PS2R_DID;
	title "segment2";
	var spend;
	class time choice;
	run;
proc means data=arec559.PS3R_DID;
	title "segment3";
	var spend;
	class time choice;
	run;
proc means data=arec559.PS4R_DID;
	title "segment4";
	var spend;
	class time choice;
	run;
proc means data=arec559.PS9R_DID;
	title "segment9";
	var spend;
	class time choice;
	run;
proc means data=arec559.PS10R_DID;
	title "segment10";
	var spend;
	class time choice;
	run;
proc means data=arec559.PS11R_DID;
	title "segment11";
	var spend;
	class time choice;
	run;


/* Standarized difference */
proc sql;
	create table PS10R_SD as
	select *
	from arec559.PS10R_DiD as a
	left join arec559.PS10 as b
	on a.cm11=b.cm11;
	quit;

proc means data=PS10R_SD noprint;
	class choice;
	where time=0;
	output out=PS10R_means;
run;
proc means data=PS10R_SD noprint;
	class choice;
	where time=0;
	output out=PS10R_means_before;run;
	
proc export
    data = PS10R_means_before
    dbms = xlsx
    outfile = "/home/asaito10/AREC559/sdPS10R_means_before.xlsx"
    replace;
run;
proc export
    data = PS10R_means
    dbms = xlsx
    outfile = "/home/asaito10/AREC559/sdPS10R_means_after.xlsx"
    replace;
run;



/* count unique cm11 */
proc sql;
	select count(distinct cm11) as cm11
	from arec559.PS10R_DiD;
	quit;