/* aggregate segment 11=5+6, 12=9+10 */
data arec559.segment12;
	set arec559.segment9 arec559.segment10;
	run;
proc contents data=arec559.segment5;
proc contents data=arec559.segment6;
proc contents data=arec559.segment11;
run;

/* segment into chooser, nonchooser*/
data arec559.segment12_chooser;
	set arec559.segment12;
	where choice=1;
	run;
data arec559.segment12_non;
	set arec559.segment12;
	where choice=0;
	run;


proc means data=arec559.segment1_chooser ;
	title "segment1_chooser";
	var transaction;
	run;
proc means data=arec559.segment1_non ;
	title "segment1_non chooser";
	var transaction;
	run;
proc means data=arec559.segment2_chooser ;
	title "segment2_chooser";
	var transaction;
	run;
proc means data=arec559.segment2_non ;
	title "segment2_non chooser";
	var transaction;
	run;
proc means data=arec559.segment3_chooser ;
	title "segment3_chooser";
	var transaction;
	run;
proc means data=arec559.segment3_non ;
	title "segment3_non chooser";
	var transaction;
	run;	
proc means data=arec559.segment4_chooser ;
	title "segment4_chooser";
	var transaction;
	run;
proc means data=arec559.segment4_non ;
	title "segment4_non chooser";
	var transaction;
	run;
proc means data=arec559.segment9_chooser ;
	title "segment9_chooser";
	var transaction;
	run;
proc means data=arec559.segment9_non ;
	title "segment9_non chooser";
	var transaction;
	run;
proc means data=arec559.segment10_chooser ;
	title "segment10_chooser";
	var transaction;
	run;
proc means data=arec559.segment10_non ;
	title "segment10_non chooser";
	var transaction;
	run;
proc means data=arec559.segment11_chooser ;
	title "segment11_chooser";
	var transaction;
	run;
proc means data=arec559.segment11_non ;
	title "segment11_non chooser";
	var transaction;
	run;
proc means data=arec559.segment12_chooser ;
	title "segment12_chooser";
	var transaction;
	run;
proc means data=arec559.segment12_non ;
	title "segment12_non chooser";
	var transaction;
	run;